export const USER_REGISTRATION_SUCCESSFULLY = 'USER_REGISTRATION_SUCCESSFULLY';
export const USER_REGISTRATION_FAILED = 'USER_REGISTRATION_FAILED';
export const GET_PROFILE_DETAIL_SUCCESSFULLY = 'GET_PROFILE_DETAIL_SUCCESSFULLY';
export const GET_PROFILE_DETAIL_FAILED = 'GET_PROFILE_DETAIL_FAILED';
