# Generated by Django 2.1.5 on 2019-04-16 17:40

from django.db import migrations
from django.contrib.auth.models import User


def create_dummy_super_user(pps, schema_editor):
    """
    creating dummy user for admin site
    :param pps:
    :param schema_editor:
    :return:
    """
    User.objects.create_superuser(
        username='super_user', password='12345678', first_name='super', last_name='user',
        email='admin@admin.com'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190319_2147'),
    ]

    operations = [
        migrations.RunPython(create_dummy_super_user)
    ]
